#!/bin/sh
#############################################################
# MAKE_TML.sh                                               #
# ......................................................... #
# This script generates Timonel bootloader images that are  #
# flashable with an AVR programmer (e.g. USBasp).           #
#                                                           #
# I know that's a bit messy, but it gets smaller images by  #
# preserving the .elf file generated by Makefile-pass-1 and #
# making it again with Makefile-pass-2 and 3. It's needless #
# to say that writing Makefiles is not my strength, so any  #
# help on this issue is very welcome.                       #
#                                                           #
# ......................................................... #
# 2018-09-09 Gustavo Casanova                               #
# ......................................................... #
# From Linux: it runs directly.                             #
# From Windows/Mac: you need to install the Git Bash tool   #
# (git-scm.com/downloads).                                  #
#                                                           #
#############################################################
echo ""
echo "##########################"
echo "#   >>> TML PASS 1 <<<   #"
echo "##########################"
cp Make-pass-1 Makefile
make clean
make all
echo ""
echo "##########################"
echo "#   >>> TML PASS 2 <<<   #"
echo "##########################"
echo ""
cp Make-pass-2 Makefile
make clean
make all
echo ""
echo "##########################"
echo "#   >>> TML PASS 3 <<<   #"
echo "##########################"
cp Make-pass-3 Makefile
make clean
make all
cp tml-bootloader.hex releases
make clean_all